In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
dataset=pd.read_csv('dataset/Churn_Modelling.csv')

In [3]:
dataset.head(5)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
x=dataset.iloc[:,3:13].values

In [5]:
y=dataset.iloc[:,13].values

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [7]:
labelencoder_x_1=LabelEncoder()

In [10]:
x[:,1]=labelencoder_x_1.fit_transform(x[:,1])

In [12]:
labelencoder_x_2=LabelEncoder()

In [13]:
x[:,2]=labelencoder_x_2.fit_transform(x[:,2])

In [14]:
onehotencoder=OneHotEncoder(categorical_features=[1])

In [15]:
x=onehotencoder.fit_transform(x).toarray()

/home/kamlesh/.local/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/kamlesh/.local/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [16]:
x=x[:,1:]

In [17]:
x.shape

(10000, 11)

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [20]:
#feature scaling

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
sc=StandardScaler()

In [23]:
x_train=sc.fit_transform(x_train)

In [24]:
x_test=sc.fit_transform(x_test)

In [25]:
x_train.shape

(8000, 11)

In [37]:
x_test.shape

(2000, 11)

In [26]:
#importing the keras library and package

In [27]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [28]:
classifier=Sequential()

In [29]:
classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11))

/home/kamlesh/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [30]:
classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))

/home/kamlesh/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [31]:
classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))

/home/kamlesh/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [32]:
#compiling the ANN

In [33]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [34]:
#Fitting to ANN to training set

In [35]:
classifier.fit(x_train,y_train,batch_size=10,nb_epoch=100)

/home/kamlesh/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
8000/8000 [==============================] - 2s 267us/step - loss: 0.4786 - acc: 0.7949
Epoch 2/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.4300 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.4272 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.4238 - acc: 0.8046
Epoch 5/100
8000/8000 [==============================] - 1s 171us/step - loss: 0.4198 - acc: 0.8227
Epoch 6/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.4172 - acc: 0.8239
Epoch 7/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.4155 - acc: 0.8295
Epoch 8/100
8000/8000 [==============================] - 1s 151us/step - loss: 0.4132 - acc: 0.8315
Epoch 9/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.4125 - acc: 0.8317
Epoch 10/100
8000/8000 [==============================] - 1s 171us/step - loss: 0.4113 - acc: 0.8335

8000/8000 [==============================] - 1s 133us/step - loss: 0.4003 - acc: 0.8357
Epoch 83/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.4003 - acc: 0.8372
Epoch 84/100
8000/8000 [==============================] - 1s 132us/step - loss: 0.4001 - acc: 0.8366
Epoch 85/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.4006 - acc: 0.8355
Epoch 86/100
8000/8000 [==============================] - 1s 134us/step - loss: 0.3997 - acc: 0.8359
Epoch 87/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.4003 - acc: 0.8356
Epoch 88/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.3995 - acc: 0.8344
Epoch 89/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.4000 - acc: 0.8366
Epoch 90/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.4001 - acc: 0.8365
Epoch 91/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.4002 - acc: 0.8336
Epo

In [38]:
y_pred=classifier.predict(x_test)

In [39]:
y_pred=(y_pred>0.5)

In [40]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [41]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [42]:
cm

array([[1544,   51],
       [ 270,  135]])

In [58]:
classifier.predict(x_test[0:3])

array([[0.19307786],
       [0.34246698],
       [0.14401162]], dtype=float32)